# Generated by Django 2.2.5 on 2019-10-03 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191003_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret',
            field=models.TextField(blank=True),
        ),
    ]
